name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # обновлено до v4
      
      - name: Set up Python
        uses: actions/setup-python@v5  # обновлено до v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet
          
      - name: Build APK with Flet
        run: |
          flet build apk chat.py --verbose
          
      - name: Upload APK
        uses: actions/upload-artifact@v4  # обновлено до v4
        with:
          name: Chat-App-APK
          path: build/apk/*.apk
          if-no-files-found: error
          retention-days: 30
